version: '3'

services:
    mlflow:
        image: ghcr.io/mlflow/mlflow
        container_name: mlflow-server
        ports:
            - "5000:5000"  
        volumes:
            - ./mlflow:/mlflow-data  
        command: >
            mlflow server  --host 0.0.0.0
            --backend-store-uri sqlite:///mlflow-data/mydb.sqlite
            --default-artifact-root /mlflow-data/artifacts
        networks:
            - app-network

    mongo:
        image: mongo
        networks:
            - app-network

    server:
        image: mlops-server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        environment:
            - MLFLOW_TRACKING_URI=http://mlflow:5000  # Utilise mlflow-server comme hôte
        depends_on:
            - mongo
            - mlflow
        networks:
            - app-network

    client:
        image: mlops-client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - 8501:8501
        depends_on:
            - mongo
        networks:
            - app-network


networks:
  app-network:
    driver: bridge